import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Masthead from '../components/masthead'
import AboutUs from "../components/aboutus"
import Skills from "../components/skills"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className="font-bold text-9xl">Hello</div> */}
      <Masthead />
      <AboutUs />
      <Skills />
    </div>
  )
}

export default Home
